### ISSUE TITLE
Trying to call non-existing module method crashes compiler

### ISSUE THREAD

**Issue by soc** [dinfuehr/dora#216]
```
SomeExistingModule::someNonExistingMethod()
```

crashes with

```
thread 'main' panicked at 'no module', dora/src/vm/module.rs:74:25
stack backtrace:
  14: core::option::Option<T>::expect
             at /rustc/212b2c7da87f3086af535b33a9ca6b5242f2d5a7/src/libcore/option.rs:347
  15: dora::vm::module::find_methods_in_module
             at dora/src/vm/module.rs:74
  16: dora::typeck::lookup::MethodLookup::find_method
             at dora/src/typeck/lookup.rs:349
  17: dora::typeck::lookup::MethodLookup::find
             at dora/src/typeck/lookup.rs:147
  18: dora::typeck::expr::TypeCheck::check_expr_call_method
             at dora/src/typeck/expr.rs:1335
  19: dora::typeck::expr::TypeCheck::check_expr_call
             at dora/src/typeck/expr.rs:1015
  20: dora::typeck::expr::TypeCheck::check_expr
             at dora/src/typeck/expr.rs:2137
  21: <dora::typeck::expr::TypeCheck as dora_parser::ast::visit::Visitor>::visit_stmt
             at dora/src/typeck/expr.rs:2170
  22: dora::typeck::expr::TypeCheck::check
             at dora/src/typeck/expr.rs:41
  23: dora::typeck::check
             at dora/src/typeck.rs:36
```

**Comment by soc** [comment]
It's kinda fixed in https://github.com/dinfuehr/dora/pull/218.

The root cause is that we loop through parents if we don't find the method in the type itself, but the loop combines those two things into one, which works for classes (= assumes all types are classes), but not for modules (= assumes all types are modules → wrong!).
